// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:petsus/api/model/auth/auth.dart' as prefix1;
import 'package:petsus/api/model/auth/auth_token.dart' as prefix2;
import 'package:petsus/api/model/clinic/clinic_list.dart' as prefix3;
import 'package:petsus/api/model/news/news.dart' as prefix4;
import 'package:petsus/api/model/user/user.dart' as prefix5;
import 'package:petsus/api/model/veterinary/veterinary_list.dart' as prefix6;
import 'package:petsus/reflection/reflection.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Auth',
            r'.Auth',
            134217735,
            0,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => ({email, password}) =>
                  b ? prefix1.Auth(email: email, password: password) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 2,
              r'toString': 0,
              r'noSuchMethod': 2,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'email': 0,
              r'password': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'AuthToken',
            r'.AuthToken',
            134217735,
            1,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => ({token, typeToken, validateToken}) => b
                  ? prefix2.AuthToken(
                      token: token,
                      typeToken: typeToken,
                      validateToken: validateToken)
                  : null,
              r'fromJson': (bool b) =>
                  (map) => b ? prefix2.AuthToken.fromJson(map) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 2,
              r'toString': 0,
              r'noSuchMethod': 2,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'validateToken': 0,
              r'typeToken': 0,
              r'token': 0,
              r'bearerToken': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'ClinicList',
            r'.ClinicList',
            134217735,
            2,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => ({page, pageCount, clinics}) => b
                  ? prefix3.ClinicList(
                      clinics: clinics, page: page, pageCount: pageCount)
                  : null,
              r'fromJson': (bool b) =>
                  (map) => b ? prefix3.ClinicList.fromJson(map) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 2,
              r'toString': 0,
              r'noSuchMethod': 2,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'page': 0,
              r'page=': 2,
              r'pageCount': 0,
              r'pageCount=': 2,
              r'clinics': 0,
              r'clinics=': 2
            }),
        r.NonGenericClassMirrorImpl(
            r'News',
            r'.News',
            134217735,
            3,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => ({id, title, image, url, date}) => b
                  ? prefix4.News(
                      date: date, url: url, id: id, image: image, title: title)
                  : null,
              r'fromJson': (bool b) =>
                  (map) => b ? prefix4.News.fromJson(map) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 2,
              r'toString': 0,
              r'noSuchMethod': 2,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'id': 0,
              r'id=': 2,
              r'title': 0,
              r'title=': 2,
              r'image': 0,
              r'image=': 2,
              r'url': 0,
              r'url=': 2,
              r'date': 0,
              r'date=': 2
            }),
        r.NonGenericClassMirrorImpl(
            r'User',
            r'.User',
            134217735,
            4,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => ({name, role}) =>
                  b ? prefix5.User(name: name, role: role) : null,
              r'fromJson': (bool b) =>
                  (map) => b ? prefix5.User.fromJson(map) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 2,
              r'toString': 0,
              r'noSuchMethod': 2,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'name': 0,
              r'role': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'VeterinaryList',
            r'.VeterinaryList',
            134217735,
            5,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => ({page, pageCount, veterinaries}) => b
                  ? prefix6.VeterinaryList(
                      page: page,
                      pageCount: pageCount,
                      veterinaries: veterinaries)
                  : null,
              r'fromJson': (bool b) =>
                  (map) => b ? prefix6.VeterinaryList.fromJson(map) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 2,
              r'toString': 0,
              r'noSuchMethod': 2,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'page': 0,
              r'page=': 2,
              r'pageCount': 0,
              r'pageCount=': 2,
              r'veterinaries': 0,
              r'veterinaries=': 2
            })
      ],
      null,
      null,
      <Type>[
        prefix1.Auth,
        prefix2.AuthToken,
        prefix3.ClinicList,
        prefix4.News,
        prefix5.User,
        prefix6.VeterinaryList
      ],
      6,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'email': (dynamic instance) => instance.email,
        r'password': (dynamic instance) => instance.password,
        r'validateToken': (dynamic instance) => instance.validateToken,
        r'typeToken': (dynamic instance) => instance.typeToken,
        r'token': (dynamic instance) => instance.token,
        r'bearerToken': (dynamic instance) => instance.bearerToken,
        r'page': (dynamic instance) => instance.page,
        r'pageCount': (dynamic instance) => instance.pageCount,
        r'clinics': (dynamic instance) => instance.clinics,
        r'id': (dynamic instance) => instance.id,
        r'title': (dynamic instance) => instance.title,
        r'image': (dynamic instance) => instance.image,
        r'url': (dynamic instance) => instance.url,
        r'date': (dynamic instance) => instance.date,
        r'name': (dynamic instance) => instance.name,
        r'role': (dynamic instance) => instance.role,
        r'veterinaries': (dynamic instance) => instance.veterinaries
      },
      {
        r'page=': (dynamic instance, value) => instance.page = value,
        r'pageCount=': (dynamic instance, value) => instance.pageCount = value,
        r'clinics=': (dynamic instance, value) => instance.clinics = value,
        r'id=': (dynamic instance, value) => instance.id = value,
        r'title=': (dynamic instance, value) => instance.title = value,
        r'image=': (dynamic instance, value) => instance.image = value,
        r'url=': (dynamic instance, value) => instance.url = value,
        r'date=': (dynamic instance, value) => instance.date = value,
        r'veterinaries=': (dynamic instance, value) =>
            instance.veterinaries = value
      },
      null,
      [
        const [0, 0, null],
        const [
          0,
          0,
          const [#email, #password]
        ],
        const [1, 0, null],
        const [
          0,
          0,
          const [#token, #typeToken, #validateToken]
        ],
        const [
          0,
          0,
          const [#page, #pageCount, #clinics]
        ],
        const [
          0,
          0,
          const [#id, #title, #image, #url, #date]
        ],
        const [
          0,
          0,
          const [#name, #role]
        ],
        const [
          0,
          0,
          const [#page, #pageCount, #veterinaries]
        ]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
